import Head from 'next/head'
import Image from 'next/image'
import AdvantageOfApp from '../Components/AdvantageOfApp'
import Carousal from '../Components/Carousal'
import Footer from '../Components/Footer'
import Navbar from '../Components/Navbar'
import NavBarBottomElement from '../Components/NavBarBottomElement'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Tin-dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='icon' href='./favicon/favicon.ico' />
        <script src="https://kit.fontawesome.com/28b667dac3.js" crossorigin="anonymous"></script>
      </Head>
      <Navbar/>
      <main className="">
      <NavBarBottomElement/>
      <AdvantageOfApp/>
      <Carousal/>
      <div className="4th"></div>
      <div className="5th"></div>
      </main>
      <Footer/>
    </div>
  )
}
